#!/bin/bash

apt-get update
apt-get install wget -y
apt-get install -y libfindbin-libs-perl
apt-get install jq -y
apt-get install perl -y
apt install python2 -y
apt install openjdk-8-jre-headless -y
apt install curl -y
apt install gzip -y
echo "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> /root/.bashrc

# download imply full
curl -O https://static.imply.io/release/imply-2021.09.tar.gz
tar -xzf imply-2021.09.tar.gz


# add license to pivot config
echo 'license: '"'"'{"name":"community-pivot","expiryDate":"2024-10-01","features":["alerts","apache-druid-compatibility","cross-tab","scheduled-reports"]}|2021-09-24|GGiGSo4WBTkSDI8tvZe1w7IBvc9pAYbgvrmjkv/5tWx6o14wS46XeIuWoNkreynY37NY+sveRZSoRCkdJCJ1mnaa1GzsSfmNgbce+lnNqndHlhIQf5Nt3c1udtyXuxuYQ4+L3n+s7s02iXXGjQYPNipJftSvStltQXrGRnypMb1xMycPWNBQVHdx8uvdR4siRiI/Rj5idfK55Wz6dJntMhBQK5rgcx0Vg1RggvVt69PvfYPNHozY/AbsWYR6va3XJwFThNvIrseCKq5YpoUI2FswJd+Uzh1zmxJG+m7s49Q/fMUKh6d8XnOu2UJze90qzSTEGmI0+Y2bs9xWACL+9A=='"'"' ' >> /root/imply-2021.09/conf-quickstart/pivot/config.yaml

rm /root/imply-2021.09/var/pivot/pivot-settings.sqlite
wget https://github.com/shallada/InstruqtImages/raw/main/pivot-db/pivot-settings.sqlite -P /root/imply-2021.09/var/pivot

#start everything
nohup /root/imply-2021.09/bin/supervise -c /root/imply-2021.09/conf/supervise/quickstart.conf  > /root/log.out 2> /root/log.err < /dev/null & disown

cat > /root/ingestion-spec.json << EOF
{
  "type": "index_parallel",
  "spec": {
    "ioConfig": {
      "type": "index_parallel",
      "inputSource": {
        "type": "http",
        "uris": [
          "https://druid.apache.org/data/wikipedia.json.gz"
        ]
      },
      "inputFormat": {
        "type": "json"
      }
    },
    "dataSchema": {
      "granularitySpec": {
        "segmentGranularity": "day",
        "queryGranularity": "none",
        "rollup": false
      },
      "dataSource": "wikipedia",
      "timestampSpec": {
        "column": "timestamp",
        "format": "iso"
      },
      "dimensionsSpec": {
        "dimensions": [
          {
            "type": "long",
            "name": "added"
          },
          "channel",
          "cityName",
          "comment",
          {
            "type": "long",
            "name": "commentLength"
          },
          "countryIsoCode",
          "countryName",
          {
            "type": "long",
            "name": "deleted"
          },
          {
            "type": "long",
            "name": "delta"
          },
          {
            "type": "long",
            "name": "deltaBucket"
          },
          "diffUrl",
          "flags",
          "isAnonymous",
          "isMinor",
          "isNew",
          "isRobot",
          "isUnpatrolled",
          "metroCode",
          "namespace",
          "page",
          "regionIsoCode",
          "regionName",
          "user"
        ]
      }
    },
    "tuningConfig": {
      "type": "index_parallel",
      "partitionsSpec": {
        "type": "dynamic"
      }
    }
  }
}
EOF

/root/imply-2021.09/bin/post-index-task \
  --file /root/ingestion-spec.json \
  --url http://localhost:8081
